apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexus-app.fullname" . }}-configs
  labels:
  {{- include "nexus-app.labels" . | nindent 4 }}
data:
  FRONTEND_URL: {{ .Values.configs.frontendUrl | quote }}
  SECURE: {{ .Values.configs.secure | quote }}
  SYSTEM_EMAIL: {{ .Values.configs.systemEmail | quote }}
