apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-app.fullname" . }}-secrets
  labels:
  {{- include "nexus-app.labels" . | nindent 4 }}
stringData:
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_SOURCE: {{ .Values.secrets.dbSource | quote }}
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MAIL_HOST: {{ .Values.secrets.mailHost | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  MAIL_PORT: {{ .Values.secrets.mailPort | quote }}
  MAIL_USERNAME: {{ .Values.secrets.mailUsername | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
type: Opaque
